spring.application.name=Souq

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

jwt.secret=GRrPxBFENUmjQ5nT7h4L9KezuDagHfJp


spring.datasource.url=jdbc:postgresql://localhost:5432/Souq
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1290
spring.h2.console.enabled=false